/**
 * OWASP Security Tests - inopay
 * Generated by InoPay NCS 2.0
 * Based on OWASP Top 10 vulnerabilities
 */
import { describe, it, expect } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';

describe('OWASP Top 10 Security Tests', () => {
  // A01:2021 – Broken Access Control
  it('should not expose admin endpoints without auth', async () => {
    const res = await fetch(`${API_URL}/api/admin`, { method: 'GET' });
    expect([401, 403, 404]).toContain(res.status);
  });
  
  // A02:2021 – Cryptographic Failures
  it('should use HTTPS headers', async () => {
    const res = await fetch(`${API_URL}/health`);
    const csp = res.headers.get('content-security-policy');
    // In dev, CSP might not be set, but should exist in production
    expect(res.ok).toBe(true);
  });
  
  // A03:2021 – Injection
  it('should sanitize path traversal', async () => {
    const res = await fetch(`${API_URL}/api/../../../etc/passwd`);
    expect([400, 403, 404]).toContain(res.status);
  });
  
  // A05:2021 – Security Misconfiguration
  it('should not expose server version', async () => {
    const res = await fetch(`${API_URL}/health`);
    const server = res.headers.get('server') || '';
    expect(server).not.toMatch(/express|nginx.*\/\d/i);
  });
  
  // A07:2021 – Identification and Authentication Failures
  it('should rate limit auth attempts', async () => {
    const attempts = await Promise.all(
      Array(10).fill(null).map(() => 
        fetch(`${API_URL}/api/auth`, { 
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email: 'test@test.com', password: 'wrong' })
        })
      )
    );
    const lastStatus = attempts[attempts.length - 1].status;
    expect([401, 429]).toContain(lastStatus);
  });
});
