/**
 * Security Tests - inopay
 * Generated by InoPay NCS 2.0
 */
import { describe, it, expect } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';

describe('Security Tests', () => {
  it('should reject SQL injection', async () => {
    const res = await fetch(`${API_URL}/api/users?id=1; DROP TABLE users;--`);
    expect(res.status).not.toBe(200);
  });
  
  it('should have CORS headers', async () => {
    const res = await fetch(`${API_URL}/health`, { method: 'OPTIONS' });
    expect(res.headers.get('access-control-allow-origin')).toBeDefined();
  });
  
  it('should reject XSS attempts', async () => {
    const res = await fetch(`${API_URL}/api/search?q=<script>alert(1)</script>`);
    const text = await res.text();
    expect(text).not.toContain('<script>');
  });
});
