

// Note: Ces imports fonctionneront dans un environnement Node.js avec les packages installés
// Pour le frontend, on utilise une version simplifiée basée sur regex

// ═══════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════

export interface RefactorPattern {
  name: string;
  description: string;
  find: RegExp | string;
  replace: string | ((match: string, ...args: string[]) => string);
  severity: 'critical' | 'major' | 'minor';
  category: 'import' | 'api' | 'pattern' | 'attribute' | 'comment';
}

export interface RefactorResult {
  originalCode: string;
  refactoredCode: string;
  changes: RefactorChange[];
  hasChanges: boolean;
  stats: {
    totalPatterns: number;
    appliedPatterns: number;
    linesChanged: number;
    bytesChanged: number;
  };
}

export interface RefactorChange {
  pattern: string;
  line: number;
  column: number;
  original: string;
  replacement: string;
  severity: 'critical' | 'major' | 'minor';
}

// ═══════════════════════════════════════════════════════════════
// PATTERNS À REMPLACER
// ═══════════════════════════════════════════════════════════════

export const REFACTOR_PATTERNS: RefactorPattern[] = [
  // ─────────────────────────────────────────────────────────────
  // IMPORTS - Critical
  // ─────────────────────────────────────────────────────────────
  {
    name: '[PLATFORM]-import',
    description: 'Import @[PLATFORM]',
    severity: 'major',
    category: 'api',
  },
  {
    name: 'sendBeacon-[PLATFORM]',
    description: 'Remove sendBeacon to [PLATFORM]',
    find: /navigator\.sendBeacon\s*\(\s*['"][^'"]*lovable[^'"]*['"]\s*(?:,\s*[^)]+)?\s*\)/gi,
    replace: '',
    severity: 'major',
    category: 'api',
  },
  {
    name: '[PLATFORM]-env-vars',
    description: 'VITE_LOVABLE_* → VITE_APP_*',
    find: /VITE_LOVABLE_([A-Z_]+)/g,
    replace: (match, varName) => `VITE_APP_${varName}`,
    severity: 'major',
    category: 'api',
  },

  // ─────────────────────────────────────────────────────────────
  // ATTRIBUTES - Minor
  // ─────────────────────────────────────────────────────────────
  {
    name: ']*"/g,
    replace: '',
    severity: 'minor',
    category: 'attribute',
  },
  {
    name: ']*"/g,
    replace: '',
    severity: 'minor',
    category: 'attribute',
  },
  {
    name: 'lov-css-class',
    description: 'Remove lov-* CSS classes',
    find: /\blov-[a-z0-9-]+/g,
    replace: '',
    severity: 'minor',
    category: 'attribute',
  },

  // ─────────────────────────────────────────────────────────────
  // COMMENTS - Minor
  // ─────────────────────────────────────────────────────────────
  {
    name: '[PLATFORM]-annotation',
    description: 'Remove @[PLATFORM]- annotations',
    find: /\/\/\s*@lovable-[a-z-]+[^\n]*/g,
    replace: '',
    severity: 'minor',
    category: 'comment',
  },
  {
    name: '[PLATFORM]-block-comment',
    description: 'Remove [PLATFORM]: block comments',
    find: /\/\*\s*lovable:[^*]*\*\//g,
    replace: '',
    severity: 'minor',
    category: 'comment',
  },
  {
    name: 'generated-by-[PLATFORM]',
    description: 'Remove "Generated by [PLATFORM]" comments',
    find: /\/\/[^\n]*[Gg]enerated\s+by\s+[Ll]ovable[^\n]*/g,
    replace: '',
    severity: 'minor',
    category: 'comment',
  }];

// ═══════════════════════════════════════════════════════════════
// AST REFACTOR CLASS
// ═══════════════════════════════════════════════════════════════

export class ASTRefactor {
  private patterns: RefactorPattern[];
  private verbose: boolean;

  constructor(options: { patterns?: RefactorPattern[]; verbose?: boolean } = {}) {
    this.patterns = options.patterns || REFACTOR_PATTERNS;
    this.verbose = options.verbose || false;
  }

  

import { z } from 'zod';
import { toast } from 'sonner';

// ═══════════════════════════════════════════════════════════════
// SOVEREIGN AI ADAPTER
// ═══════════════════════════════════════════════════════════════

export const sovereignAIAdapter = {
  async generateCompletion(prompt: string, options: {
    model?: string;
    temperature?: number;
    maxTokens?: number;
  } = {}) {
    const AI_URL = import.meta.env.VITE_AI_URL || 'http://localhost:11434';
    const model = options.model || 'llama3.2';
    
    const response = await fetch(\`\${AI_URL}/api/generate\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model,
        prompt,
        stream: false,
        options: {
          temperature: options.temperature || 0.7,
          num_predict: options.maxTokens || 2048,
        },
      }),
    });
    
    const data = await response.json();
    return { text: data.response, usage: { tokens: data.eval_count } };
  },

  async createAssistant(config: { name: string; instructions: string }) {
    return { id: crypto.randomUUID(), ...config };
  },

  async run(assistantId: string, input: string) {
    return this.generateCompletion(input);
  },
};

// ═══════════════════════════════════════════════════════════════
// PATTERN REPLACEMENTS
// ═══════════════════════════════════════════════════════════════

export function createTemplateEngine() {
  return {
    render: (template: string, data: Record<string, any>) => {
      return template.replace(/\\{\\{(\\w+)\\}\\}/g, (_, key) => data[key] || '');
    },
    compile: (template: string) => (data: Record<string, any>) => {
      return template.replace(/\\{\\{(\\w+)\\}\\}/g, (_, key) => data[key] || '');
    },
  };
}

export function createStateManager<T>(initial: T) {
  let state = initial;
  const listeners = new Set<(state: T) => void>();
  
  return {
    get: () => state,
    set: (newState: T) => {
      state = newState;
      listeners.forEach(fn => fn(state));
    },
    subscribe: (fn: (state: T) => void) => {
      listeners.add(fn);
      return () => listeners.delete(fn);
    },
  };
}

export function createRouter() {
  return {
    navigate: (path: string) => window.location.href = path,
    back: () => window.history.back(),
    forward: () => window.history.forward(),
  };
}

export function createFormHandler() {
  return {
    handleSubmit: (fn: (data: any) => void) => (e: Event) => {
      e.preventDefault();
      const form = e.target as HTMLFormElement;
      const data = Object.fromEntries(new FormData(form));
      fn(data);
    },
  };
}

export function createModalManager() {
  let isOpen = false;
  const listeners = new Set<(open: boolean) => void>();
  
  return {
    open: () => { isOpen = true; listeners.forEach(fn => fn(true)); },
    close: () => { isOpen = false; listeners.forEach(fn => fn(false)); },
    toggle: () => { isOpen = !isOpen; listeners.forEach(fn => fn(isOpen)); },
    isOpen: () => isOpen,
    onOpenChange: (fn: (open: boolean) => void) => {
      listeners.add(fn);
      return () => listeners.delete(fn);
    },
  };
}

// Re-export common utilities
export { z, toast };

// Default API object
export const api = {
  get: async (url: string) => fetch(url).then(r => r.json()),
  post: async (url: string, data: any) => fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  }).then(r => r.json()),
};
`;
}

export default ASTRefactor;
