/**
 * E2E Smoke Tests - inopay
 * Generated by InoPay NCS 2.0
 */
import { describe, it, expect, beforeAll } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';
const APP_URL = process.env.APP_URL || 'http://localhost:5173';

describe('E2E Smoke Tests', () => {
  beforeAll(async () => {
    // Wait for services to be ready
    let attempts = 0;
    while (attempts < 30) {
      try {
        const res = await fetch(`${API_URL}/health`);
        if (res.ok) break;
      } catch (e) {
        await new Promise(r => setTimeout(r, 1000));
        attempts++;
      }
    }
  });
  
  it('API health check passes', async () => {
    const res = await fetch(`${API_URL}/health`);
    expect(res.ok).toBe(true);
    const data = await res.json();
    expect(data.status).toBe('healthy');
  });
  
  it('Frontend serves HTML', async () => {
    const res = await fetch(APP_URL);
    expect(res.ok).toBe(true);
    expect(res.headers.get('content-type')).toContain('text/html');
  });

  it('Route admin_list_payments is reachable', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_payments`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route admin_list_subscriptions is reachable', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_subscriptions`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route admin_list_users is reachable', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_users`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route admin_manage_subscription is reachable', async () => {
    const res = await fetch(`${API_URL}/api/admin_manage_subscription`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route admin_manage_tester is reachable', async () => {
    const res = await fetch(`${API_URL}/api/admin_manage_tester`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
});
