// Test Setup - Generated by InoPay NCS 2.0
import { beforeAll, afterAll, vi } from 'vitest';

// Mock fetch if running in Node without native fetch
if (typeof globalThis.fetch === 'undefined') {
  // @ts-ignore - fetch is polyfilled in Node 18+
  global.fetch = vi.fn();
}

beforeAll(() => {
  console.log('🧪 Starting test suite...');
});

afterAll(() => {
  console.log('✅ Test suite completed');
});
