/**
 * Smoke Tests - inopay
 * Generated by InoPay Liberation Pack NCS
 */
import { describe, it, expect } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';

describe('API Smoke Tests', () => {
  it('health check', async () => {
    const res = await fetch(`${API_URL}/health`);
    expect(res.status).toBe(200);
  });

  it('admin_list_payments responds', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_payments`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_list_subscriptions responds', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_subscriptions`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_list_users responds', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_users`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_manage_subscription responds', async () => {
    const res = await fetch(`${API_URL}/api/admin_manage_subscription`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_manage_tester responds', async () => {
    const res = await fetch(`${API_URL}/api/admin_manage_tester`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_signout_all responds', async () => {
    const res = await fetch(`${API_URL}/api/admin_signout_all`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('auto_configure_coolify_app responds', async () => {
    const res = await fetch(`${API_URL}/api/auto_configure_coolify_app`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('auto_fix_dockerfile responds', async () => {
    const res = await fetch(`${API_URL}/api/auto_fix_dockerfile`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('auto_restart_container responds', async () => {
    const res = await fetch(`${API_URL}/api/auto_restart_container`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('check_deployment_status responds', async () => {
    const res = await fetch(`${API_URL}/api/check_deployment_status`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
});