/**
 * Integration Tests - inopay
 * Generated by InoPay NCS 2.0
 */
import { describe, it, expect } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';

describe('API Integration Tests', () => {
  it('health check should respond', async () => {
    const res = await fetch(`${API_URL}/health`);
    expect(res.ok).toBe(true);
  });

  it('admin_list_payments should respond', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_payments`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_list_subscriptions should respond', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_subscriptions`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_list_users should respond', async () => {
    const res = await fetch(`${API_URL}/api/admin_list_users`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_manage_subscription should respond', async () => {
    const res = await fetch(`${API_URL}/api/admin_manage_subscription`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_manage_tester should respond', async () => {
    const res = await fetch(`${API_URL}/api/admin_manage_tester`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('admin_signout_all should respond', async () => {
    const res = await fetch(`${API_URL}/api/admin_signout_all`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('audit should respond', async () => {
    const res = await fetch(`${API_URL}/api/audit`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('auto_configure_coolify_app should respond', async () => {
    const res = await fetch(`${API_URL}/api/auto_configure_coolify_app`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('auto_fix_dockerfile should respond', async () => {
    const res = await fetch(`${API_URL}/api/auto_fix_dockerfile`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('auto_restart_container should respond', async () => {
    const res = await fetch(`${API_URL}/api/auto_restart_container`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
});
