/**
 * useToast Hook - Toast notification wrapper for sonner
 * Generated by InoPay Liberation Pack
 * 
 * This provides compatibility with useToast pattern while using sonner
 */
import { toast as sonnerToast } from 'sonner';

export interface ToastProps {
  title?: string;
  description?: string;
  variant?: 'default' | 'destructive';
  duration?: number;
}

export function toast(props: ToastProps | string) {
  if (typeof props === 'string') {
    sonnerToast(props);
    return;
  }

  const { title, description, variant, duration } = props;
  const message = title || description || '';
  const options = { description: title ? description : undefined, duration };

  if (variant === 'destructive') {
    sonnerToast.error(message, options);
  } else {
    sonnerToast(message, options);
  }
}

export function useToast() {
  return { toast };
}

// Re-export sonner toast for direct usage
export { toast as sonnerToast } from 'sonner';
