#!/bin/bash
# Import secrets to Hashicorp Vault - inopay
# Generated by InoPay NCS 2.0

set -e

VAULT_ADDR=${VAULT_ADDR:-http://localhost:8200}
PROJECT_NAME="inopay"

echo "🔐 Importing secrets to Vault..."

# Read from .env and import
while IFS='=' read -r key value; do
  if [[ ! -z "$key" && ! "$key" =~ ^# ]]; then
    echo "  → Storing $key"
    vault kv put "secret/$PROJECT_NAME/$key" value="$value"
  fi
done < .env

echo "✅ Secrets imported successfully!"
echo "   Path: secret/$PROJECT_NAME/"
